/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as tabsRouteRouteImport } from './routes/(tabs)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as tabsIndexRouteImport } from './routes/(tabs)/index'
import { Route as tabsSearchIndexRouteImport } from './routes/(tabs)/search/index'
import { Route as tabsProfileIndexRouteImport } from './routes/(tabs)/profile/index'
import { Route as tabsFavoritesIndexRouteImport } from './routes/(tabs)/favorites/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'

const tabsRouteRoute = tabsRouteRouteImport.update({
  id: '/(tabs)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsIndexRoute = tabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => tabsRouteRoute,
} as any)
const tabsSearchIndexRoute = tabsSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => tabsRouteRoute,
} as any)
const tabsProfileIndexRoute = tabsProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => tabsRouteRoute,
} as any)
const tabsFavoritesIndexRoute = tabsFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => tabsRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof tabsIndexRoute
  '/about': typeof AboutIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/favorites': typeof tabsFavoritesIndexRoute
  '/profile': typeof tabsProfileIndexRoute
  '/search': typeof tabsSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof tabsIndexRoute
  '/about': typeof AboutIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/favorites': typeof tabsFavoritesIndexRoute
  '/profile': typeof tabsProfileIndexRoute
  '/search': typeof tabsSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(tabs)': typeof tabsRouteRouteWithChildren
  '/(tabs)/': typeof tabsIndexRoute
  '/about/': typeof AboutIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(tabs)/favorites/': typeof tabsFavoritesIndexRoute
  '/(tabs)/profile/': typeof tabsProfileIndexRoute
  '/(tabs)/search/': typeof tabsSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/sign-in' | '/favorites' | '/profile' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sign-in' | '/favorites' | '/profile' | '/search'
  id:
    | '__root__'
    | '/(auth)'
    | '/(tabs)'
    | '/(tabs)/'
    | '/about/'
    | '/(auth)/sign-in/'
    | '/(tabs)/favorites/'
    | '/(tabs)/profile/'
    | '/(tabs)/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  tabsRouteRoute: typeof tabsRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(tabs)': {
      id: '/(tabs)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof tabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/': {
      id: '/(tabs)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof tabsIndexRouteImport
      parentRoute: typeof tabsRouteRoute
    }
    '/(tabs)/search/': {
      id: '/(tabs)/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof tabsSearchIndexRouteImport
      parentRoute: typeof tabsRouteRoute
    }
    '/(tabs)/profile/': {
      id: '/(tabs)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof tabsProfileIndexRouteImport
      parentRoute: typeof tabsRouteRoute
    }
    '/(tabs)/favorites/': {
      id: '/(tabs)/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof tabsFavoritesIndexRouteImport
      parentRoute: typeof tabsRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface tabsRouteRouteChildren {
  tabsIndexRoute: typeof tabsIndexRoute
  tabsFavoritesIndexRoute: typeof tabsFavoritesIndexRoute
  tabsProfileIndexRoute: typeof tabsProfileIndexRoute
  tabsSearchIndexRoute: typeof tabsSearchIndexRoute
}

const tabsRouteRouteChildren: tabsRouteRouteChildren = {
  tabsIndexRoute: tabsIndexRoute,
  tabsFavoritesIndexRoute: tabsFavoritesIndexRoute,
  tabsProfileIndexRoute: tabsProfileIndexRoute,
  tabsSearchIndexRoute: tabsSearchIndexRoute,
}

const tabsRouteRouteWithChildren = tabsRouteRoute._addFileChildren(
  tabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  tabsRouteRoute: tabsRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
